name: CI
on:
  - push

jobs:
  build:
    name: Build shared library with demo file
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and tests
        run: |
          mkdir -p build && cd build
          echo "symbol_shim undefined_symbol, actual_symbol" >> shim_demo
          cmake -DSYMBOLS_SHIM_PATH=$(pwd)/shim_demo ..
          make VERBOSE=1
          nm --defined-only libshim.so | grep undefined_symbol
          nm --undefined-only libshim.so | grep actual_symbol
